import { describe, expect, it } from "vitest";
import { buildAgentPackage, requiredPackageArtifactsPresent, verifyAgentPackageBytes } from "../../src/package/agent-package.js";
import { evaluationFor, validAgentSpecContent } from "../fixtures/specs.js";
import { computeContentHash } from "../../src/assembler/content-hash.js";
import { forgePackageWithMismatchedEmbeddedEvidence, forgePackageWithStaleSpecHash } from "../support/package-forgery.js";

function approved(spec = validAgentSpecContent) { return { type: "agent_spec", artifactId: "approval-package-001", requestedBy: "agent-builder", decision: "approved", decidedBy: "konstantin", decidedAt: "2026-07-27T08:00:00+02:00", specId: spec.specId, version: spec.version, contentHash: spec.contentHash, evidence: { policyOutcome: "approved_pending_gate", delta: "initial", evaluationRef: evaluationFor(spec) } }; }
describe("versioned agent package", () => {
  it("creates deterministic ZIP bytes with required evidence artifacts", () => { const input = { spec: validAgentSpecContent, approval: approved(), evaluation: evaluationFor(validAgentSpecContent) }; const first = buildAgentPackage(input); expect(first.fileName).toBe("spec-crm-enricher-1.0.0.zip"); expect(first.bytes.slice(0, 4)).toEqual(Uint8Array.of(0x50, 0x4b, 0x03, 0x04)); expect(first.sha256).toBe(buildAgentPackage(input).sha256); expect(requiredPackageArtifactsPresent(first.manifest)).toBe(true); });
  it("rejects foreign evidence and credential markers", () => { const evaluation = evaluationFor(validAgentSpecContent); expect(() => buildAgentPackage({ spec: validAgentSpecContent, approval: { ...approved(), contentHash: "other" }, evaluation })).toThrow("approval does not bind"); const { contentHash: _previousHash, ...unsafeBase } = { ...validAgentSpecContent, promptTemplate: "Use password=fixture." }; const unsafe = { ...unsafeBase, contentHash: computeContentHash(unsafeBase) }; expect(() => buildAgentPackage({ spec: unsafe, approval: approved(unsafe), evaluation: evaluationFor(unsafe) })).toThrow("prohibited"); });
  it("recomputes and rejects a forged Spec content hash", () => { const forged = { ...validAgentSpecContent, objective: "Modified objective while retaining the declared hash." }; expect(() => buildAgentPackage({ spec: forged, approval: approved(forged), evaluation: evaluationFor(forged) })).toThrow("spec content hash"); });
  it("rejects approval/evaluation replay when the embedded evaluation differs", () => { const evaluation = evaluationFor(validAgentSpecContent); const replayed = { ...evaluation, evidenceId: "evidence-replayed" }; const approval = { ...approved(), evidence: { ...approved().evidence, evaluationRef: replayed } }; expect(() => buildAgentPackage({ spec: validAgentSpecContent, approval, evaluation })).toThrow("approval does not bind"); });
  it("rejects a structurally valid ZIP with mismatched embedded approval/evaluation evidence", () => { const evaluation = evaluationFor(validAgentSpecContent); const value = forgePackageWithMismatchedEmbeddedEvidence({ spec: validAgentSpecContent, approval: approved(), evaluation }); expect(verifyAgentPackageBytes(value.bytes)).toMatchObject({ success: false, reason: "embedded_evidence_binding_mismatch" }); });
  it("rejects a structurally valid ZIP whose embedded Spec retains a stale hash", () => { const value = forgePackageWithStaleSpecHash({ spec: validAgentSpecContent, approval: approved(), evaluation: evaluationFor(validAgentSpecContent) }); expect(verifyAgentPackageBytes(value.bytes)).toMatchObject({ success: false, reason: "embedded_spec_content_hash_mismatch" }); });
  it("fails closed when an actual ZIP artifact byte is tampered", () => { const value = buildAgentPackage({ spec: validAgentSpecContent, approval: approved(), evaluation: evaluationFor(validAgentSpecContent) }); const tampered = value.bytes.slice(); tampered[50]! ^= 1; expect(verifyAgentPackageBytes(tampered)).toMatchObject({ success: false }); });
  it("fails closed when the ZIP central directory is tampered", () => { const value = buildAgentPackage({ spec: validAgentSpecContent, approval: approved(), evaluation: evaluationFor(validAgentSpecContent) }); const tampered = value.bytes.slice(); const central = tampered.findIndex((_, index) => index + 4 <= tampered.length && tampered[index] === 0x50 && tampered[index + 1] === 0x4b && tampered[index + 2] === 0x01 && tampered[index + 3] === 0x02); tampered[central + 16]! ^= 1; expect(verifyAgentPackageBytes(tampered)).toMatchObject({ success: false }); });
  it("fails closed for duplicate central-directory names", () => {
    const value = buildAgentPackage({ spec: validAgentSpecContent, approval: approved(), evaluation: evaluationFor(validAgentSpecContent) }); const tampered = value.bytes.slice();
    const findLast = (needle: string) => { const encoded = new TextEncoder().encode(needle); for (let index = tampered.length - encoded.length; index >= 0; index -= 1) if (encoded.every((byte, offset) => tampered[index + offset] === byte)) return index; return -1; };
    const approvalName = findLast("approval.json"); const manifestName = findLast("manifest.json"); const approval = approvalName - 46; const manifest = manifestName - 46;
    tampered.set(tampered.slice(approval + 16, approval + 28), manifest + 16); tampered.set(tampered.slice(approval + 42, approval + 46), manifest + 42); tampered.set(tampered.slice(approvalName, approvalName + 13), manifestName);
    expect(verifyAgentPackageBytes(tampered)).toMatchObject({ success: false });
  });
});
