import {
  createRoadmapBaseReconciliationProofV1,
  ROADMAP_RECONCILIATION_POLICY_DIGEST,
  type RoadmapBaseReconciliationProofV1,
} from "../../src/orchestration/roadmap-reconciliation.js";

export const PR18_MERGE_SHA = "aeec5a84d0dd3ae16bfad39b81cc74291be0002f";
export const WORKFLOW_MANIFEST_DIGEST = "cf76aa31ea735049165136709028f69e07c82b80c1ee3eb40a0078ef61e8553d";

export function bootstrapReconciliationProof(): RoadmapBaseReconciliationProofV1 {
  return createRoadmapBaseReconciliationProofV1({
    schemaVersion: "roadmap-base-reconciliation-proof/1",
    policyDigest: ROADMAP_RECONCILIATION_POLICY_DIGEST,
    domainBaseSha: "b3244c73ca79c68dbba3b4a05234f93d3ed92752",
    observedOriginMainSha: PR18_MERGE_SHA,
    commits: [
      {
        schemaVersion: "transparent-meta-commit-proof/1",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: "b3244c73ca79c68dbba3b4a05234f93d3ed92752",
        mergeCommitSha: "ce8c4ba614347f408715cdb3fe0dfc1ce128466a",
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 17,
        pullRequestHeadSha: "66cd6f414a88b82b0a75e395d3a8dfaa33f744db",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T10:44:38Z",
        requiredCheck: {
          name: "verify",
          headSha: "66cd6f414a88b82b0a75e395d3a8dfaa33f744db",
          conclusion: "success",
        },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          ".gitignore",
          "README.md",
          "contracts/autonomous-roadmap-orchestration-v0.1.json",
          "docs/architecture/autonomous-roadmap-orchestration-v0.1.md",
          "roadmap/agent-builder-roadmap.v1.json",
          "src/orchestration/adapters.ts",
          "src/orchestration/canonical-json.ts",
          "src/orchestration/claude-cli-negotiator.ts",
          "src/orchestration/contracts.ts",
          "src/orchestration/controller.ts",
          "src/orchestration/index.ts",
          "src/orchestration/model-routing.ts",
          "src/orchestration/persistence.ts",
          "src/orchestration/reducer.ts",
          "src/orchestration/roadmap.ts",
          "tests/orchestration/canonical-model-routing.test.ts",
          "tests/orchestration/claude-cli-negotiator.test.ts",
          "tests/orchestration/controller.test.ts",
          "tests/orchestration/persistence.test.ts",
          "tests/orchestration/reducer.test.ts",
          "tests/orchestration/roadmap.test.ts",
          "tests/orchestration/support.ts",
        ].sort(),
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
      {
        schemaVersion: "transparent-meta-commit-proof/1",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: "ce8c4ba614347f408715cdb3fe0dfc1ce128466a",
        mergeCommitSha: PR18_MERGE_SHA,
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 18,
        pullRequestHeadSha: "cbc3240ec454c3dcc1b869e42a528936d236eff2",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T14:23:26Z",
        requiredCheck: {
          name: "verify",
          headSha: "cbc3240ec454c3dcc1b869e42a528936d236eff2",
          conclusion: "success",
        },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          "README.md",
          "contracts/host-workflow-adapters-v0.1.json",
          "contracts/workflow-safety-manifest.v1.json",
          "docs/architecture/autonomous-roadmap-orchestration-v0.1.md",
          "docs/architecture/host-workflow-adapters-v0.1.md",
          "src/orchestration/host-workflow-claude-negotiator.ts",
          "src/orchestration/host-workflow-contracts.ts",
          "src/orchestration/host-workflow-controller.ts",
          "src/orchestration/host-workflow-persistence.ts",
          "src/orchestration/host-workflow-reducer.ts",
          "src/orchestration/index.ts",
          "src/orchestration/workflow-adapters.ts",
          "tests/orchestration/host-workflow-claude-negotiator.test.ts",
          "tests/orchestration/host-workflow-contracts.test.ts",
          "tests/orchestration/host-workflow-controller.test.ts",
          "tests/orchestration/host-workflow-persistence.test.ts",
        ].sort(),
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
    ],
  });
}
