import {
  createRoadmapBaseReconciliationProofV1,
  createRoadmapBaseReconciliationProofV2,
  ROADMAP_RECONCILIATION_POLICY_DIGEST,
  ROADMAP_RECONCILIATION_POLICY_V2_DIGEST,
  type RoadmapBaseReconciliationProofV1,
  type RoadmapBaseReconciliationProofV2,
} from "../../src/orchestration/roadmap-reconciliation.js";

export const PR18_MERGE_SHA = "aeec5a84d0dd3ae16bfad39b81cc74291be0002f";
export const WORKFLOW_MANIFEST_DIGEST = "cf76aa31ea735049165136709028f69e07c82b80c1ee3eb40a0078ef61e8553d";

export function bootstrapReconciliationProof(): RoadmapBaseReconciliationProofV1 {
  return createRoadmapBaseReconciliationProofV1({
    schemaVersion: "roadmap-base-reconciliation-proof/1",
    policyDigest: ROADMAP_RECONCILIATION_POLICY_DIGEST,
    domainBaseSha: "b3244c73ca79c68dbba3b4a05234f93d3ed92752",
    observedOriginMainSha: PR18_MERGE_SHA,
    commits: [
      {
        schemaVersion: "transparent-meta-commit-proof/1",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: "b3244c73ca79c68dbba3b4a05234f93d3ed92752",
        mergeCommitSha: "ce8c4ba614347f408715cdb3fe0dfc1ce128466a",
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 17,
        pullRequestHeadSha: "66cd6f414a88b82b0a75e395d3a8dfaa33f744db",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T10:44:38Z",
        requiredCheck: {
          name: "verify",
          headSha: "66cd6f414a88b82b0a75e395d3a8dfaa33f744db",
          conclusion: "success",
        },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          ".gitignore",
          "README.md",
          "contracts/autonomous-roadmap-orchestration-v0.1.json",
          "docs/architecture/autonomous-roadmap-orchestration-v0.1.md",
          "roadmap/agent-builder-roadmap.v1.json",
          "src/orchestration/adapters.ts",
          "src/orchestration/canonical-json.ts",
          "src/orchestration/claude-cli-negotiator.ts",
          "src/orchestration/contracts.ts",
          "src/orchestration/controller.ts",
          "src/orchestration/index.ts",
          "src/orchestration/model-routing.ts",
          "src/orchestration/persistence.ts",
          "src/orchestration/reducer.ts",
          "src/orchestration/roadmap.ts",
          "tests/orchestration/canonical-model-routing.test.ts",
          "tests/orchestration/claude-cli-negotiator.test.ts",
          "tests/orchestration/controller.test.ts",
          "tests/orchestration/persistence.test.ts",
          "tests/orchestration/reducer.test.ts",
          "tests/orchestration/roadmap.test.ts",
          "tests/orchestration/support.ts",
        ].sort(),
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
      {
        schemaVersion: "transparent-meta-commit-proof/1",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: "ce8c4ba614347f408715cdb3fe0dfc1ce128466a",
        mergeCommitSha: PR18_MERGE_SHA,
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 18,
        pullRequestHeadSha: "cbc3240ec454c3dcc1b869e42a528936d236eff2",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T14:23:26Z",
        requiredCheck: {
          name: "verify",
          headSha: "cbc3240ec454c3dcc1b869e42a528936d236eff2",
          conclusion: "success",
        },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          "README.md",
          "contracts/host-workflow-adapters-v0.1.json",
          "contracts/workflow-safety-manifest.v1.json",
          "docs/architecture/autonomous-roadmap-orchestration-v0.1.md",
          "docs/architecture/host-workflow-adapters-v0.1.md",
          "src/orchestration/host-workflow-claude-negotiator.ts",
          "src/orchestration/host-workflow-contracts.ts",
          "src/orchestration/host-workflow-controller.ts",
          "src/orchestration/host-workflow-persistence.ts",
          "src/orchestration/host-workflow-reducer.ts",
          "src/orchestration/index.ts",
          "src/orchestration/workflow-adapters.ts",
          "tests/orchestration/host-workflow-claude-negotiator.test.ts",
          "tests/orchestration/host-workflow-contracts.test.ts",
          "tests/orchestration/host-workflow-controller.test.ts",
          "tests/orchestration/host-workflow-persistence.test.ts",
        ].sort(),
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
    ],
  });
}

export const PR19_MERGE_SHA = "b833e63303ac8f3e0218f01523b4ab611db76e08";
export const PR20_MERGE_SHA = "6f637285c77054b17abca40c18f42c7f615d9be4";
export const PR21_MERGE_SHA = "d".repeat(40);

export function bootstrapReconciliationProofV2(): RoadmapBaseReconciliationProofV2 {
  const v1 = bootstrapReconciliationProof();
  const commits = v1.commits.map(({ schemaVersion: _ignored, ...commit }) => ({
    ...commit,
    schemaVersion: "transparent-meta-commit-proof/2" as const,
  }));
  return createRoadmapBaseReconciliationProofV2({
    schemaVersion: "roadmap-base-reconciliation-proof/2",
    policyDigest: ROADMAP_RECONCILIATION_POLICY_V2_DIGEST,
    domainBaseSha: v1.domainBaseSha,
    observedOriginMainSha: PR21_MERGE_SHA,
    commits: [
      ...commits,
      {
        schemaVersion: "transparent-meta-commit-proof/2",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: PR18_MERGE_SHA,
        mergeCommitSha: PR19_MERGE_SHA,
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 19,
        pullRequestHeadSha: "b4c29264258e6a783bbff3f9906f23a27dbb9c71",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T17:21:55Z",
        requiredCheck: { name: "verify", headSha: "b4c29264258e6a783bbff3f9906f23a27dbb9c71", conclusion: "success" },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          "README.md",
          "contracts/roadmap-base-reconciliation-v0.1.json",
          "docs/architecture/autonomous-roadmap-orchestration-v0.1.md",
          "docs/architecture/roadmap-base-reconciliation-v0.1.md",
          "roadmap/agent-builder-roadmap.v1.json",
          "src/orchestration/adapters.ts",
          "src/orchestration/claude-cli-negotiator.ts",
          "src/orchestration/contracts.ts",
          "src/orchestration/controller.ts",
          "src/orchestration/index.ts",
          "src/orchestration/reducer.ts",
          "src/orchestration/roadmap-reconciliation.ts",
          "src/orchestration/roadmap.ts",
          "tests/orchestration/claude-cli-negotiator.test.ts",
          "tests/orchestration/controller.test.ts",
          "tests/orchestration/persistence.test.ts",
          "tests/orchestration/reconciliation-support.ts",
          "tests/orchestration/reducer.test.ts",
          "tests/orchestration/roadmap-reconciliation.test.ts",
          "tests/orchestration/roadmap.test.ts",
        ],
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
      {
        schemaVersion: "transparent-meta-commit-proof/2",
        source: "github_pull_request",
        mergeMethod: "merge",
        parentSha: PR19_MERGE_SHA,
        mergeCommitSha: PR20_MERGE_SHA,
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 20,
        pullRequestHeadSha: "fcf2af8008a87cda4d9d1dfc55dc920fcd2be7b0",
        pullRequestState: "merged",
        mergedAt: "2026-07-24T19:42:29Z",
        requiredCheck: { name: "verify", headSha: "fcf2af8008a87cda4d9d1dfc55dc920fcd2be7b0", conclusion: "success" },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: [
          "README.md",
          "contracts/human-attended-contract-lock-v0.1.json",
          "docs/architecture/human-attended-contract-lock-v0.1.md",
          "src/orchestration/contracts.ts",
          "src/orchestration/human-attested-contract-negotiator.ts",
          "src/orchestration/index.ts",
          "src/orchestration/reducer.ts",
          "tests/orchestration/human-attested-contract-negotiator.test.ts",
        ],
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
      {
        schemaVersion: "transparent-meta-commit-proof/2",
        source: "github_pull_request",
        mergeMethod: "squash",
        parentSha: PR20_MERGE_SHA,
        mergeCommitSha: PR21_MERGE_SHA,
        mergeCommitReachableFromOriginMain: true,
        mergeCommitTreeMatchesPullRequestHead: true,
        pullRequestNumber: 21,
        pullRequestHeadSha: "e".repeat(40),
        pullRequestState: "merged",
        mergedAt: "2026-07-25T10:00:00Z",
        requiredCheck: { name: "verify", headSha: "e".repeat(40), conclusion: "success" },
        workflowSafetyManifestDigest: WORKFLOW_MANIFEST_DIGEST,
        changedPaths: ["README.md"],
        capabilityEffect: "reduce_or_preserve",
        deploymentEffect: "none",
      },
    ],
  });
}
